### ISSUE TITLE
I need help to use cached_object

### ISSUE THREAD

**Issue by ozonosphere** [pyxll/pyxll-utils#5]
I have pyxll installed, how to I start using your objectcache.

Is there any complete tutorial to show me how to import the module etc, 

I would appreciate it if you could help.

Thanks

Charles

**Comment by tonyroberts** [comment]
Hi,

there is an object cache example included in the PyXLL examples that come as part of the PyXLL download. The code in this package is pretty much identical to that example. The downloaded package also contains an Excel file that uses the object cache example. The docs for that example are here:
https://www.pyxll.com/docs/index.html#object-cache

To use the object cache code from this package, all you need to do is to include it in the modules list in your pyxll.cfg file, e.g.:

```
[PYXLL]
modules = pyxll_utils.object_cache
```

Once you've done that, in your own code you will be able to use 'cached_object' as a return type to return a reference to a cached python object to an Excel cell, and 'cached_object' as an argument type to a function that will receive the cached object.

Best regards,
Tony
